ARG IMAGE_ARCH=linux/arm64

ARG BASE_NAME=weston-vivante

ARG IMAGE_TAG=3

ARG DOCKER_REGISTRY=torizon

FROM --platform=$IMAGE_ARCH $DOCKER_REGISTRY/$BASE_NAME:$IMAGE_TAG AS base

COPY weston.ini /etc/xdg/weston/
